# Generated by Django 4.1.2 on 2022-10-28 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_comment_author_alter_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='сreation_date',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='сreation_date',
            new_name='creation_date',
        ),
    ]
