# Generated by Django 4.1.2 on 2022-12-16 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='announced',
        ),
    ]
